# Generated by Django 5.2.1 on 2025-05-18 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lower_tunnel', models.FloatField(default=0)),
                ('upper_tunnel', models.FloatField(default=0)),
                ('tracking_frequency', models.IntegerField(default=5, help_text='Check frequency (minutes)')),
                ('email', models.EmailField(max_length=254)),
                ('notify_only_once', models.BooleanField(default=False)),
                ('notified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PriceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_records', to='tracker.asset')),
            ],
        ),
    ]
