# Generated by Django 5.2.1 on 2025-05-15 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('stock', 'Stock / ETF / BDR'), ('future', 'Future'), ('index', 'Index'), ('idi', 'IDI'), ('itc', 'ITC')], max_length=20)),
                ('tunnel_type', models.CharField(choices=[('static', 'Static'), ('dynamic_sync', 'Dynamic Synchronous'), ('dynamic_async', 'Dynamic Unsynchronous')], max_length=20)),
                ('volatility', models.FloatField()),
                ('strike_price', models.FloatField()),
                ('expiration_days', models.IntegerField()),
                ('interest_rate', models.FloatField(default=0.13)),
                ('email', models.EmailField(max_length=254)),
                ('last_price', models.FloatField(blank=True, null=True)),
                ('notified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PriceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_records', to='tracker.asset')),
            ],
        ),
    ]
