# Generated by Django 5.2.1 on 2025-05-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='notify_only_once',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='tracking_frequency',
            field=models.IntegerField(default=5, help_text='Frequency to check the asset (minutes)'),
        ),
    ]
