# Generated by Django 5.2.1 on 2025-05-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='last_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
