# Generated by Django 5.2.1 on 2025-05-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_asset_last_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='tunnel_input_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('percentage', 'Percentage')], default='manual', max_length=20),
        ),
    ]
