# Generated by Django 5.2.1 on 2025-05-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_asset_notify_only_once_asset_tracking_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_type',
        ),
        migrations.AddField(
            model_name='asset',
            name='lower_tunnel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='upper_tunnel',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
