# Generated by Django 5.2.1 on 2025-05-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_asset_asset_type_asset_lower_tunnel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='option_type',
            field=models.CharField(choices=[('call', 'Call'), ('put', 'Put')], default='call', max_length=4),
        ),
    ]
