# Generated by Django 5.2.1 on 2025-05-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_asset_option_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='option_type',
            field=models.CharField(choices=[('call', 'Call'), ('put', 'Put')], max_length=4),
        ),
    ]
