services:
  web:
    container_name: web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com     
      PGADMIN_DEFAULT_PASSWORD: admin           
    ports:
      - "5050:80"                               
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  db:
    container_name: db
    ports:
      - "5432:5432"
    image: postgres:15
    environment:
      POSTGRES_USER: 'guibastos'
      POSTGRES_PASSWORD: 'inoa123'
      POSTGRES_HOST: 'db'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6379"

  celery:
    container_name: celery
    build: .
    command: celery -A mysite worker --loglevel=info
    depends_on:
      - web
      - redis

  celery-beat:
    container_name: celery_beat
    build: .
    command: celery -A mysite beat --loglevel=info
    depends_on:
      - web
      - redis
      
volumes:
  pgdata:
  pgadmin-data: