services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

    celery:
    build: .
    command: celery -A mysite worker --loglevel=info
    depends_on:
      - web
      - redis
  celery-beat:
    build: .
    command: celery -A mysite beat --loglevel=info
    depends_on:
      - web
      - redis
      
volumes:
  pgdata: